# Generated by Django 3.2.3 on 2021-06-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataModels',
            new_name='Algorithm',
        ),
        migrations.RenameModel(
            old_name='Algorithms',
            new_name='DataModel',
        ),
        migrations.RenameField(
            model_name='algorithm',
            old_name='data_model',
            new_name='algorithm_name',
        ),
        migrations.RenameField(
            model_name='datamodel',
            old_name='algorithm',
            new_name='datamodel_name',
        ),
    ]
